# Generated by Django 4.2.16 on 2024-11-04 20:30

from django.db import migrations, models
import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_additionalprofile_avatar_additionalprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.data_validatiors.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='additionalprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.data_validatiors.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.data_validatiors.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.data_validatiors.validate_phone_number], verbose_name='phone number'),
        ),
    ]
